### ISSUE TITLE
Adding more than 20 torrents at the same time

### ISSUE THREAD

**Issue by src7** [scaleway/image-app-torrents#11]
I got the impression that when you upload more than 20 torrent files, only the first 20 are added in fact.

**Comment by src7** [comment]
Also a (only one tested) 1Mo+ torrent doesn't work.

**Comment by brmzkw** [comment]
For the 1MB+, it has already been fixed by https://github.com/scaleway/image-app-torrents/commit/7a9cc6a6078c4137a69bf6e4848558c43bd886fa

We will release a new image soon.
