### ISSUE TITLE
Setup SFTP

### ISSUE THREAD

**Issue by moul** [scaleway/image-app-torrents#14]

**Comment by brmzkw** [comment]
I prefered to setup FTPS instead of SFTP, because configuring SFTP is a bit more difficult since users in `/var/www/credentials` aren't UNIX users and it would require to tweak `/etc/pam.d/sshd`.

To use ftps with curl:

`curl -k --ftp-ssl-reqd -u <LOGIN>:<PASS> ftp://<SERVER_IP>`

**Comment by moul** [comment]
#21
