### ISSUE TITLE
Setup FTP server

### ISSUE THREAD

**Issue by brmzkw** [scaleway/image-app-torrents#2]
It would be nice to have a FTP server that lists the files downloaded

**Comment by aimxhaisse** [comment]
:+1: 

This could be handful for the python image, the LEMP image, as well as the Wordpress image, so if this can be generic, that would be perfect :)

**Comment by brmzkw** [comment]
sure

**Comment by src7** [comment]
Or SFTP, WebDav users... (propositions only)

**Comment by NoKriK** [comment]
We should push toward secure protocols, software like Cyperduck support SFTP out of the box.

**Comment by moul** [comment]
SFTP dedicated issue: https://github.com/scaleway/image-app-torrents/issues/14
