### ISSUE TITLE
Setup media reader

### ISSUE THREAD

**Issue by brmzkw** [scaleway/image-app-torrents#3]
Setup https://plex.tv/ and/or something opensource

**Comment by moul** [comment]
:+1: :heart:

**Comment by moul** [comment]
http://www.htpcguides.com/install-plex-media-server-on-raspberry-pi-2/

**Comment by moul** [comment]
I succeed to manually install Plex, it does not support all features but I can stream some 1080p videos from the seedbox to my home player.

I created a separated issue (#8) because I think we should add plex alongside another media reader

**Comment by brmzkw** [comment]
[I installed](https://github.com/scaleway/image-app-torrents/commit/0917418a7deff22582d1a41c32a5353c921e4057) h5ai to improve the directory listing on `http://<ip>/downloads.` h5ai has a feature to view text and video files online, so I guess the feature can be closed :-)
